### PR TITLE
Docs: build with Sphinx 6.x

### PR DESCRIPTION
**Pull request by humitos**
Sphinx 6.x does not include jQuery, but since we are now depending on `sphinxcontrib-jquery` it should be added.

cc @benjaoming 

----
:books: Documentation preview :books:: https://sphinx-hoverxref--242.org.readthedocs.build/en/242/

----
:books: Documentation preview :books:: https://read-the-docs-sphinx-hoverxref--242.com.readthedocs.build/en/242/

### CODE REVIEW

**Comment by humitos** [comment]
He he, I was not able to upgrade Sphinx to 6.x because of `docutils` 🙃 

```
$ pip-compile --extra=doc --output-file=docs/requirements.txt pyproject.toml
Could not find a version that matches docutils<0.18,<0.20,>=0.18,>=0.8,~=0.17.0 (from sphinx-tabs==3.3.1->sphinx-hoverxref (pyproject.toml))
Tried: 0.3, 0.3.5, 0.3.7, 0.3.9, 0.4, 0.5, 0.6, 0.7, 0.8, 0.8.1, 0.9, 0.9.1, 0.10, 0.11, 0.12, 0.12, 0.13.1, 0.13.1, 0.14, 0.14, 0.15, 0.15, 0.15.1.post1, 0.15.2, 0.15.2, 0.16, 0.16, 0.17, 0.17, 0.17.1, 0.17.1, 0.18, 0.18, 0.18.1, 0.18.1, 0.19, 0.19
Skipped pre-versions: 0.14rc1, 0.14rc2, 0.16b0.dev0, 0.16b0.dev0, 0.16rc1, 0.16rc1, 0.17b1, 0.17b1, 0.17.1b1.dev0, 0.17.1b1.dev0, 0.18b1, 0.18b1, 0.18.1b0, 0.18.1b0, 0.19b1, 0.19b1
There are incompatible versions in the resolved dependencies:
  docutils>=0.8 (from sphinxcontrib-bibtex==2.5.0->sphinx-hoverxref (pyproject.toml))
  docutils<0.20,>=0.18 (from sphinx==6.0.0b2->sphinx-hoverxref (pyproject.toml))
  docutils~=0.17.0 (from sphinx-tabs==3.3.1->sphinx-hoverxref (pyproject.toml))
  docutils<0.18 (from sphinx-rtd-theme==1.0.0->sphinx-hoverxref (pyproject.toml))
```

**Comment by benjaoming** [comment]
ah yes, we should do a pre-release once the 1.1 is out

@agjohnson noting that the 1.1 theme release is clogging up more

**Comment by ericholscher** [comment]
Why does Sphinx 6 require docutils >0.18? That might be worth bringing up with the Sphinx folks.

**Comment by humitos** [comment]
@ericholscher I found this commit that drops support for docutils<0.18: https://github.com/sphinx-doc/sphinx/commit/bb62d2a2ee7d6d4b79b269c837ebf8d57aee0795

It does not explain too much, but I suppose it's to avoid the maintainability cost overhead that it implies.

**Comment by ericholscher** [comment]
Seems merging `main` fixed this? What changed?

**Comment by humitos** [comment]
Nope, the build is not using the 6.x version.

**Pull request closed without merging**
