### PR TITLE
Support tooltips in :numref:

### LINKED ISSUE #70: Anyway to support tooltips for internal references created by numref?
Thanks for a great wee tool :) 

I'm having trouble combining the `numref` role with tooltips - does it perhaps need another round of rendering in the same way that mathjax panels do?  My conf.py file looks like this:
```
hoverxref_auto_ref = True
hoverxref_roles = ['ref', 'numref']
hoverxref_role_types = {
    'ref': 'tooltip',       
    'numref': 'tooltip',    
}
```
The pages are working fine for things which use the `ref` role, just not the `numref` one.  

Readthedocs site is here: https://cellml-specification-dev.readthedocs.io/en/i314_numref_hoverxref/reference/formal_and_informative/specB09.html

If you have any suggestions I'd be very glad to hear them.  Thanks!

### PR DESCRIPTION
**Pull request by humitos**
Closes #70

### CODE REVIEW

**Comment by kerimoyle** [comment]
Thanks very much :)

**Comment by kerimoyle** [comment]
Hi again - Do you know when you're likely to have a new release version (in particular, one that includes this update)?  I'd like to be able to pin it into our project nicely :)

**Comment by humitos** [comment]
@kerimoyle I don't have an ETA. I wanted to get #68 merged as well, but that requires some extra work in the server as well that I need to finish testing. Hopefully this happens next week :)

**Comment by kerimoyle** [comment]
Hey there @humitos! Just wanted to check in about getting a release version containing #71 ? Hope you're well ... thanks :)

**Comment by humitos** [comment]
Thanks for pinging back. It's on my TODO list. Hopefully, I can get into this today or this week.

**Comment by humitos** [comment]
@kerimoyle I just uploaded `0.4b1` to PyPI. Please, let me know if everything works as you expected! :smile:

**Comment by kerimoyle** [comment]
Yes! Hurrah! All working nicely.  Thanks so much 😄

**Pull request merged**
