### PR TITLE
Handle explicit intersphinx inventory names in all domains

### PR DESCRIPTION
**Pull request by shiftinv**
Intersphinx supports explicitly specifying the inventory name in a link target, e.g. the `python:` part in ``:ref:`python:datetime-datetime` ``.

The custom `missing_reference` hook in hoverxref handles such target names as well, but only in the `std` domain (as far as I can tell, particularly for `:ref:`, which is in the `std` domain).

Intersphinx supports target names with explicit inventories regardless of role/domain, which means ``:py:attr:`python:datetime.time.minute` `` results in the correct link, but without the hoverxref popup as the `python:` prefix isn't handled by hoverxref in this case.

---
This PR attempts to fix this by removing the check for the `std` domain, which I believe intersphinx also [doesn't check](https://github.com/sphinx-doc/sphinx/blob/4d90277c/sphinx/ext/intersphinx.py#L295-L300).

I'm very much not sure if this makes sense with how Sphinx, Intersphinx and sphinx-hoverxref interact, or if there are side-effects, I don't know a whole lot about Sphinx internals :sweat_smile: Nevertheless, this fixes the aforementioned issue, and tests pass fine :)

The difference between sphinx-hoverxref 1.2.0 and this PR can be seen here:
- https://sphinx-test-stuff.readthedocs.io/en/hoverxref-intersphinx/
- https://sphinx-test-stuff.readthedocs.io/en/hoverxref-intersphinx-fixed/

Note the difference on the second `:attr:` link, while hovering over the second `:ref:` link works in both versions.

----
:books: Documentation preview :books:: https://sphinx-hoverxref--236.org.readthedocs.build/en/236/

----
:books: Documentation preview :books:: https://read-the-docs-sphinx-hoverxref--236.com.readthedocs.build/en/236/

### CODE REVIEW

**Comment by onerandomusername** [comment]
Would you mind updating this to be based on version 1.2.0?

**Review by humitos — APPROVED** [review]
Wow @shiftinv! I'm pressed of the quality of this PR. The description is awesome, the live examples and the code! Thanks a lot for working on this 🤗 

I don't remember exactly why I made the decision to only check for `std` domain. I suppose it was a way to protect myself while coding this because I don't have a strong knowledge of Sphinx internals either. However, I think it's find and seems safe to accept this change since Sphinx itself is doing something pretty similar.

I will release 1.3.0 soon.

**Comment by humitos** [comment]
@shiftinv @onerandomusername I just released 1.3.0. Please, let me know if it works as you expected 💯

**Comment by shiftinv** [comment]
@humitos Awesome, much appreciated! Everything seems to be working fine, all references are now being found :tada:

**Pull request merged**
